# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#01_about"
  weight = 1

[[main]]
  name = "News"
  url = "#02_recent-news"
  weight = 2

[[main]]
  name = "Publications"
  url = "#03_international-publications"
  weight = 3

[[main]]
  name = "Talks"
  url = "#06_talks"
  weight = 4

[[main]]
  name = "Awards & Grants"
  url = "#07_awards-and-grants"
  weight = 5

[[main]]
  name = "Posts"
  url = "#08_featured"
  weight = 6

[[main]]
  name = "Experience"
  url = "#10_experience"
  weight = 7

[[main]]
  name = "Projects"
  url = "#11_projects"
  weight = 8



# [[main]]
#   name = "Contact"
#   url = "#contact"
#   weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
